Repository forkcms/forkcms, pull requests merged in 2018-12, with the labels that each got.

#2688 Composer update symfony/phpunit-bridge
  composer.lock
Labels: Bug, Critical

#2689 Don't set the row parameter in the Categories action's datagrid
  src/Backend/Modules/Faq/Actions/Categories.php
Labels: Bug

#2693 Remove cleanup of media library
  src/Backend/Modules/MediaLibrary/Actions/MediaItemCleanup.php
  src/Backend/Modules/MediaLibrary/Console/MediaItemDeleteAllCommand.php
  src/Backend/Modules/MediaLibrary/Installer/Data/locale.xml
  src/Backend/Modules/MediaLibrary/Installer/Installer.php
  src/Backend/Modules/MediaLibrary/Js/MediaLibrary.js
  src/Backend/Modules/MediaLibrary/Layout/Templates/MediaItemIndex.html.twig
  src/Backend/Modules/MediaLibrary/Manager/MediaItemManager.php
  src/Backend/Modules/MediaLibrary/Resources/config/console.yml
  tests/data/test_db.sql
Labels: Critical

#2696 Use correct check for blog detail revision
  src/Frontend/Modules/Blog/Actions/Detail.php
Labels: Bug, Critical

#2625 Create a TitleType to easily add titles to your Fork CMS form!
  src/Backend/Modules/ContentBlocks/Domain/ContentBlock/ContentBlockType.php
  src/Backend/Modules/MediaGalleries/Domain/MediaGallery/MediaGalleryType.php
  src/Common/Form/TitleType.php
Labels: Feature

#2626 Update form layout with panels
  src/Backend/Core/Layout/Templates/FormLayout.html.twig
  src/Backend/Modules/ContentBlocks/Layout/Templates/Add.html.twig
  src/Backend/Modules/Mailmotor/Domain/Settings/SettingsType.php
  src/Backend/Modules/Mailmotor/Layout/Templates/Settings.html.twig
Labels: Enhancement

#2653 Prevent installation of a theme if it contains .tpl files
  src/Backend/Modules/Extensions/Actions/InstallTheme.php
  src/Backend/Modules/Extensions/Installer/Data/locale.xml
Labels: Enhancement

#2649 Only build the navigation cache if vital information has changed
  src/Backend/Modules/Pages/Actions/Edit.php
Labels: Enhancement

#2703 Improve the thumbnail generation console command
  src/Console/Thumbnails/GenerateThumbnailsCommand.php
Labels: Enhancement
