Repository forkcms/forkcms, pull requests merged in 2018-07, with the labels that each got.

#2579 Remove obsolete <link rel="stylesheet"
  src/Frontend/Core/Layout/Templates/Mails/Default.html.twig
Labels: Enhancement

#2519 Lazy load media library twig extension `media_library_widget`
  src/Backend/Modules/MediaLibrary/Resources/config/services.yml
  src/Frontend/Modules/MediaLibrary/Twig/AppRuntime.php
  src/Frontend/Modules/MediaLibrary/Twig/Extensions/FrontendHelperExtensions.php
Labels: Enhancement, Media Library

#2585 Set the default language for tests to 'en'
  app/config/config_test.yml
Labels: Bug
