Repository forkcms/forkcms, pull requests merged in 2018-03, with the labels that each got.

#2502 Replace some leftover cancelButton macros with a buttonIcon implementation
  src/Backend/Modules/Profiles/Layout/Templates/Add.html.twig
  src/Backend/Modules/Profiles/Layout/Templates/AddGroup.html.twig
  src/Backend/Modules/Profiles/Layout/Templates/AddProfileGroup.html.twig
  src/Backend/Modules/Profiles/Layout/Templates/EditGroup.html.twig
Labels: Bug, Critical

#2507 Delete entries linked to a deleted group
  src/Backend/Modules/Groups/Engine/Model.php
Labels: Bug

#2504 Remove role tree that prevent screenreaders to use this page
  src/Backend/Modules/Groups/Layout/Templates/Add.html.twig
  src/Backend/Modules/Groups/Layout/Templates/Edit.html.twig
Labels: Bug

#2508 Fix check if user belongs to a certain group
  src/Backend/Modules/Groups/Engine/Model.php
Labels: Bug

#2503 Ensure getRandomString() returns a string with the requested length
  src/Frontend/Modules/Profiles/Engine/Model.php
Labels: Bug

#2517 2496 dont ask to comment if commenting is not allowed
  src/Frontend/Modules/Blog/Layout/Templates/Detail.html.twig
Labels: Blog, Enhancement

#2498 Module Blog. Update Category.html.twig if article with image too short.
  src/Frontend/Modules/Blog/Layout/Templates/Category.html.twig
Labels: Blog

#2483 Add referrer security header
  src/Common/EventListener/ResponseSecurer.php
Labels: Enhancement

#2499 CKEDITOR / Update Link dialog with internal pages
  src/Backend/Core/Js/ckeditor/plugins/medialibrary/dialogs/linkDialog.js
Labels: Enhancement

#2500 Wcag update pages block actions
  src/Backend/Core/Installer/Data/locale.xml
  src/Backend/Modules/Pages/Js/Pages.js
Labels: Enhancement

#2505 Set a label and for attr for each form field in blog add/edit
  src/Backend/Modules/Blog/Layout/Templates/Add.html.twig
  src/Backend/Modules/Blog/Layout/Templates/Edit.html.twig
Labels: Enhancement

#2506 Wcag update tags input help text
  src/Backend/Core/Installer/Data/locale.xml
  src/Backend/Modules/Blog/Actions/Add.php
  src/Backend/Modules/Blog/Actions/Edit.php
  src/Backend/Modules/Blog/Layout/Templates/Add.html.twig
  src/Backend/Modules/Blog/Layout/Templates/Edit.html.twig
  src/Backend/Modules/Pages/Actions/Add.php
  src/Backend/Modules/Pages/Actions/Edit.php
  src/Backend/Modules/Pages/Layout/Templates/Add.html.twig
  src/Backend/Modules/Pages/Layout/Templates/Edit.html.twig
Labels: Enhancement

#2501 Set aria label on subnavigation
  src/Backend/Core/Engine/Navigation.php
  src/Backend/Core/Layout/Templates/base.html.twig
Labels: Enhancement

#2511 Disable console debug logging when running tests
  app/config/config_test.yml
Labels: Enhancement
