Repository forkcms/forkcms, pull requests merged in 2018-11, with the labels that each got.

#2669 Tag fixes
  src/Backend/Modules/Tags/Engine/Model.php
  src/Backend/Modules/Tags/Installer/Data/locale.xml
Labels: Bug, Tags

#2672 Add missing use statement
  src/Backend/Modules/Locale/Actions/Export.php
Labels: Bug, Critical

#2673 Fix case of DateTime class name usage
  src/Backend/Modules/MediaGalleries/Domain/MediaGallery/MediaGallery.php
  src/Backend/Modules/MediaLibrary/Domain/MediaFolder/MediaFolder.php
  src/Backend/Modules/MediaLibrary/Domain/MediaGroup/MediaGroup.php
  src/Backend/Modules/MediaLibrary/Domain/MediaItem/MediaItem.php
Labels: Bug
