Repository forkcms/forkcms, pull requests merged in 2018-05, with the labels that each got.

#2529 Add early return instead of obsolete variable declaration
  src/Backend/Modules/Extensions/Engine/Model.php
Labels: Enhancement

#2532 Add CurlPost to Google Recaptcha
  src/Frontend/Modules/FormBuilder/Widgets/Form.php
Labels: Enhancement, FormBuilder

#2526 Fix for Backend Analytics Charts
  src/Backend/Modules/Analytics/Js/Analytics.js
Labels: Analytics, Bug

#2537 Fix tabbing to permission panels
  src/Backend/Core/Layout/Css/screen.css
  src/Backend/Core/Layout/Css/screen.css.map
  src/Backend/Core/Layout/Sass/components/_panels.scss
  src/Backend/Modules/Groups/Layout/Templates/Edit.html.twig
Labels: a11y

#2542 Add sr-only text for the breadcrumb
  src/Frontend/Core/Layout/Templates/Breadcrumb.html.twig
Labels: Enhancement, a11y
