Repository forkcms/forkcms, pull requests merged in 2019-08, with the labels that each got.

#2875 Use the correct icon for deleting a ContentBlock
  src/Backend/Modules/ContentBlocks/Layout/Templates/Edit.html.twig
Labels: Bug

#2873 Change arrow function to a plain old function
  src/Frontend/Core/Js/frontend.js
Labels: Bug, Critical

#2874 Convert + to %20 in mailto urls
  src/Backend/Core/Js/ckeditor/plugins/medialibrary/dialogs/linkDialog.js
Labels: Bug

#2878 Make the PageContextDataCollector ignore all errors
  src/Common/DataCollector/PageContextDataCollector.php
Labels: DX
