Repository forkcms/forkcms, pull requests merged in 2020-11, with the labels that each got.

#3209 Add slack icon to Readme
  README.md
  docs/01. installation/04. webservers.md
Labels: hacktoberfest-accepted

#3208 Fix scrutinizer & coverage upload
  .github/workflows/run-tests.yml
  .scrutinizer.yml
  README.md
Labels: hacktoberfest-accepted

#3212 Set cache policy for woff2
  .htaccess
Labels: Enhancement, Has PR

#3226 Bugfix consent dialog
  src/Backend/Modules/Settings/Actions/Index.php
Labels: Bug, Has PR
